# coderabbit-config.yaml
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  function_name_review:
    enabled: false
    criteria:
      - "clarity"
      - "consistency"
      - "conventions"
      - "verbs_only"
  path_instructions:
    - path: "**/*.java"
      instructions: |
        Review the the function name in the class and function names should be verb.    
chat:
  auto_reply: true
